//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projecto_PrograVI_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Usuario
    {
        public string Cedula { get; set; }
        public string Nacionalidad { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Apellido2 { get; set; }
        public string Correo { get; set; }
        public string Num_Tarjeta { get; set; }
        public string Nom_Tarjeta { get; set; }
        public string Codigo_Tarj { get; set; }
        public Nullable<System.DateTime> Fecha_Exp_Tarj { get; set; }
        public string Provincia { get; set; }
        public string Canton { get; set; }
        public string Distrito { get; set; }
        public string Clave { get; set; }
        public Nullable<bool> RecordarClave { get; set; }
        public string Privilegios { get; set; }
        public string Pregunta_Seg { get; set; }
    }
}
